-- アナリストコメント統合テーブル（Supabase SQL Editor で1回実行）
create table if not exists analyst_comments (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('nikkei_option', 'stock_signal', 'crypto_signal')),
  comment_date date not null,
  title text,
  content text not null,
  metadata jsonb,
  created_at timestamp with time zone default now(),
  unique (source, comment_date)
);

create index if not exists analyst_comments_date_idx
  on analyst_comments (comment_date desc);

create index if not exists analyst_comments_source_idx
  on analyst_comments (source);
