-- ARIA ハブ用テーブル（Supabase SQL Editorで1回実行）
-- 順一さんの日次リクエスト・相談事
create table if not exists aria_daily_requests (
  id bigint generated by default as identity primary key,
  date date not null,
  content text not null,
  source text default 'claude_chat',
  created_at timestamp with time zone default now()
);
create index if not exists aria_daily_requests_date_idx
  on aria_daily_requests (date desc);

-- 競合チャンネルのGemini分析結果
create table if not exists aria_benchmark_insights (
  id bigint generated by default as identity primary key,
  analysis_date date not null,
  channel_name text not null,
  video_title text,
  focus_themes text,
  source_url text,
  created_at timestamp with time zone default now()
);
create index if not exists aria_benchmark_insights_date_idx
  on aria_benchmark_insights (analysis_date desc);
