-- ARIA向け「月次比較・日米連動」インサイト用テーブル（Supabase SQL Editor で1回実行）
create table if not exists aria_daily_insights (
  id bigint generated by default as identity primary key,
  date date not null unique,
  facts jsonb not null,
  sp500_change_pct_1m numeric,
  sp500_change_pct_3m numeric,
  nasdaq_change_pct_1m numeric,
  nasdaq_change_pct_3m numeric,
  sector_changes jsonb,
  comovement jsonb,
  created_at timestamp with time zone default now()
);

create index if not exists aria_daily_insights_date_idx
  on aria_daily_insights (date desc);
