-- 日経225オプション朝サマリー用テーブル（Supabase SQL Editor で1回実行）
create table if not exists nikkei_option_morning_summary (
  id bigint generated by default as identity primary key,
  date date not null unique,
  nikkei_close numeric,
  nikkei_change_pct numeric,
  nikkei_vi numeric,
  sp500_close numeric,
  sp500_change_pct numeric,
  vix_close numeric,
  usdjpy numeric,
  sq_days_remaining integer,
  summary_text text,
  created_at timestamp with time zone default now()
);

create index if not exists nikkei_option_morning_summary_date_idx
  on nikkei_option_morning_summary (date desc);
